#! /bin/sh -e
case $# in
0) echo "Usage: dmodify filename"; exit 1;;
1) ;;
*) echo "Usage: dmodify filename"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
# 
#
set -e
trap 'cd $savedir; exit' 0
#
#
#
#
#
cd doc/source
( $RBS_DEDITOR $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/doc/source/$1 ) &
#
cd $savedir
trap 0
