#! /bin/sh -e
#
case $# in
0) echo "Usage: sdrag fromrelease componentname"; exit 1;;
1) echo "Usage: sdrag fromrelease componentname"; exit 1;;
*) ;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
#
#
#
trap '' 1 2 3
#
trap 'echo "SDRAG: No sdrag allowed during your other grabs"; umask 22; cd $savedir; exit 2' 0
umask 222
( echo "  " > $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/grab.rbs ) 2> /dev/null
umask 22
#
#
set -e
trap 'echo "SDRAG: No sdrag allowed during your integrate"; rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/grab.rbs ; cd $savedir; exit 2' 0
if ( test -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/integrate.rbs )
then exit 0
fi
if ( test -f $1/integrate.rbs )
then exit 0
fi
#
#
set -e 
trap 'echo "SDRAG: Error during sdrag" ; rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/grab.rbs ; cd $savedir ; exit 2' 0
#
#
#
if ( test "$2" = "actions" )
then cd actions
     mv $1/$2/* .
else cd $2/source
     mv $1/$2/source/* .
fi
#
#
rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/grab.rbs
cd $savedir
trap 0
