#define S_Empty 0
#define S_AmbiguousWords 1
#define S_EnterSentence 2
#define S_ChangeInput 3
#define S_StartMessage 4
#define S_MenuNext 5
#define S_MenuNextLex 6
#define S_MenuNextStruct 7
#define S_MenuNextLexNext 8
#define S_MenuNextStructNext 9
#define S_MenuAllNext 10
#define S_MenuNextStructLex 11
#define S_MenuStopNew 12
#define S_ERROR_ASegm 20
#define S_ERROR_ALextree 21
#define S_ERROR_InCorrectRuleName 22
#define S_ERROR_UnknownStreeSpec 23
#define S_ERROR_InCorrectNode 24
#define S_ERROR_NoTreesFound 25
#define S_ERROR_NoLastRule 26
#define S_ERROR_NoNodeSelected 27
#define S_ERROR_NoAttrSelected 28
#define S_ERROR_NoExtraInfo 29
#define S_ERROR_NoAttributes 30
#define S_ERROR_MaxNrScreens 31
#define S_QUESTION_Exit 32
#define S_QUESTION_ZeroMeanings 33
