#define MAX_SCREENS      10
#define SCREEN_OFFSET    ( SCREEN_END - SCREEN_START )
#define X_LAST           ( SCREEN_START + MAX_SCREENS * SCREEN_OFFSET )
#define X_undefined 0
#define X_mw_window 1
#define X_mw_input_area 2
#define X_mw_output_area 3
#define X_mw_message_text 4
#define X_mw_analysis_frame 5
#define X_mw_generation_frame 6
#define X_mw_alayout_text 7
#define X_mw_amorph_text 8
#define X_mw_sparser_text 9
#define X_mw_mparser_text 10
#define X_mw_atrans_text 11
#define X_mw_gtrans_text 12
#define X_mw_mgeneration_text 13
#define X_mw_linearizer_text 14
#define X_mw_gmorph_text 15
#define X_mw_glayout_text 16
#define X_mw_translate_button 17
#define X_mw_anext_button 18
#define X_mw_inspect_button 19
#define X_mw_continue_button 20
#define X_mw_nextstruct_button 21
#define X_mw_nextlex_button 22
#define X_mw_gnext_button 23
#define X_mw_new_button 24
#define X_mw_modify_button 25
#define X_mw_exit_button 26
#define X_mw_dbgset_button 27
#define X_mw_env_button 28
#define X_mw_help_button 29
#define X_mw_keys_button 30
#define X_mw_tutorial_button 31
#define X_mw_version_button 32
#define X_question_window 33
#define X_question_ok_button 34
#define X_question_cancel_button 35
#define X_err_window 36
#define X_err_ok_button 37
#define X_file_window 38
#define X_file_ok_button 39
#define X_file_cancel_button 40
#define X_startup_window 41
#define X_help_window 42
#define X_help_area 43
#define X_help_ok_button 44
#define X_help_help_button 45
#define X_amb1_window 46
#define X_amb1_ok_button 47
#define X_amb1_help_button 48
#define X_amb1_stem1_text 49
#define X_amb1_mean1_list 50
#define X_amb2_window 51
#define X_amb2_ok_button 52
#define X_amb2_help_button 53
#define X_amb2_stem1_text 54
#define X_amb2_stem2_text 55
#define X_amb2_mean1_list 56
#define X_amb2_mean2_list 57
#define X_amb3_window 58
#define X_amb3_ok_button 59
#define X_amb3_help_button 60
#define X_amb3_stem1_text 61
#define X_amb3_stem2_text 62
#define X_amb3_stem3_text 63
#define X_amb3_mean1_list 64
#define X_amb3_mean2_list 65
#define X_amb3_mean3_list 66
#define X_dbg_window 67
#define X_dbg_area 68
#define X_dbg_ok_button 69
#define X_dbg_hold_button 70
#define X_dbg_tofile_button 71
#define X_dbg_help_button 72
#define X_dbgset_window 73
#define X_dbgset_ok_button 74
#define X_dbgset_reset_button 75
#define X_dbgset_help_button 76
#define X_dbgset_debug1_toggle 77
#define X_dbgset_debug2_toggle 78
#define X_dbgset_debug3_toggle 79
#define X_dbgset_debug4_toggle 80
#define X_dbgset_debug5_toggle 81
#define X_dbgset_debug6_toggle 82
#define X_dbgset_debug7_toggle 83
#define X_dbgset_debug8_toggle 84
#define X_dbgset_print1_toggle 85
#define X_dbgset_print2_toggle 86
#define X_dbgset_print3_toggle 87
#define X_dbgset_print4_toggle 88
#define X_dbgset_print5_toggle 89
#define X_dbgset_print6_toggle 90
#define X_dbgset_print7_toggle 91
#define X_dbgset_print8_toggle 92
#define X_dbgset_interact1_toggle 93
#define X_dbgset_interact2_toggle 94
#define X_dbgset_interact3_toggle 95
#define X_dbgset_interact4_toggle 96
#define X_dbgset_interact5_toggle 97
#define X_dbgset_interact6_toggle 98
#define X_dbgset_interact7_toggle 99
#define X_dbgset_interact8_toggle 100
#define X_dbgset_last1_toggle 101
#define X_dbgset_last2_toggle 102
#define X_dbgset_last3_toggle 103
#define X_dbgset_last4_toggle 104
#define X_dbgset_last5_toggle 105
#define X_dbgset_last6_toggle 106
#define X_dbgset_last7_toggle 107
#define X_dbgset_last8_toggle 108
#define X_env_window 109
#define X_env_ok_button 110
#define X_env_reset_button 111
#define X_env_help_button 112
#define X_env_alang1_toggle 113
#define X_env_alang2_toggle 114
#define X_env_glang1_toggle 115
#define X_env_glang2_toggle 116
#define X_env_glang3_toggle 117
#define X_env_alex1_toggle 118
#define X_env_alex2_toggle 119
#define X_env_glex1_toggle 120
#define X_env_glex2_toggle 121
#define X_env_aprog1_toggle 122
#define X_env_aprog2_toggle 123
#define X_env_gprog1_toggle 124
#define X_env_gprog2_toggle 125
#define X_mp_window 126
#define X_mp_rule_sel_list 127
#define X_mp_rule_info_list 128
#define X_mp_rule_scroll_text 129
#define X_mp_rule_add_text 130
#define X_mp_rule_remove_button 131
#define X_mp_rule_clear_button 132
#define X_mp_trans_sel_list 133
#define X_mp_trans_info_list 134
#define X_mp_trans_scroll_text 135
#define X_mp_trans_add_text 136
#define X_mp_trans_remove_button 137
#define X_mp_trans_clear_button 138
#define X_mp_tree_toggle 139
#define X_mp_trace_toggle 140
#define X_mp_start_button 141
#define X_mp_step_button 142
#define X_mp_stop_button 143
#define X_mp_treein_button 144
#define X_mp_treeout_button 145
#define X_mp_help_button 146
#define X_mg_window 147
#define X_mg_rule_sel_list 148
#define X_mg_rule_info_list 149
#define X_mg_rule_scroll_text 150
#define X_mg_rule_add_text 151
#define X_mg_rule_last_button 152
#define X_mg_rule_remove_button 153
#define X_mg_rule_clear_button 154
#define X_mg_trans_sel_list 155
#define X_mg_trans_info_list 156
#define X_mg_trans_scroll_text 157
#define X_mg_trans_add_text 158
#define X_mg_trans_last_button 159
#define X_mg_trans_remove_button 160
#define X_mg_trans_clear_button 161
#define X_mg_tree_toggle 162
#define X_mg_trace_toggle 163
#define X_mg_start_button 164
#define X_mg_step_button 165
#define X_mg_stop_button 166
#define X_mg_stopall_button 167
#define X_mg_treein_button 168
#define X_mg_treeout_button 169
#define X_mg_help_button 170
#define X_mps_window 171
#define X_mps_appliedrules_text 172
#define X_mps_triedrules_text 173
#define X_mps_treerules_text 174
#define X_mps_successfilters_text 175
#define X_mps_treefilters_text 176
#define X_mps_totalfilters_text 177
#define X_mps_cpu_text 178
#define X_mps_ok_button 179
#define X_mps_help_button 180
#define X_le_window 181
#define X_le_help_window 182
#define X_le_help_button_box 183
#define X_le_help_area 184
#define X_le_current_button 185
#define X_le_frozen_button 186
#define X_le_local_button 187
#define X_le_dutch_button 188
#define X_le_english_button 189
#define X_le_spanish_button 190
#define X_le_exit_button 191
#define X_le_find_lemma_button 192
#define X_le_modify_lemma_button 193
#define X_le_copy_lemma_button 194
#define X_le_insert_lemma_button 195
#define X_le_sequential_button 196
#define X_le_insert_meaning_button 197
#define X_le_insert_particle_button 198
#define X_le_insert_idiom_button 199
#define X_le_insert_semi_idiom_button 200
#define X_le_delete_lemma_button 201
#define X_le_translate_dutch_button 202
#define X_le_translate_english_button 203
#define X_le_translate_spanish_button 204
#define X_le_show_idioms_button 205
#define X_le_show_semi_idioms_button 206
#define X_le_help_button 207
#define X_le_language 208
#define X_le_mean_list 209
#define X_le_part_list 210
#define X_le_sid_list 211
#define X_le_id_list 212
#define X_le_attr_list 213
#define X_le_comment_text 214
#define X_le_message_text 215
#define X_le_stem_text 216
#define X_le_category_text 217
#define X_le_skey 218
#define X_le_analysis_toggle 219
#define X_le_generation_toggle 220
#define X_le_angen_toggle 221
#define X_le_sjwa_toggle 222
#define X_le_wissel_toggle 223
#define X_le_cons_toggle 224
#define X_le_gg_toggle 225
#define X_le_ch_toggle 226
#define X_le_kk_toggle 227
#define X_le_th_toggle 228
#define X_le_previous_button 229
#define X_le_next_button 230
#define X_le_jump_button 231
#define X_le_return_button 232
#define X_le_select_button 233
#define X_le_selected_number 234
#define X_le_current_lemma 235
#define X_le_help_ok_button 236
#define X_le_select_window 237
#define X_le_select_stem 238
#define X_le_select_category 239
#define X_le_select_ok_button 240
#define X_le_select_cancel_button 241
#define X_le_select_help_button 242
#define X_le_il_window 243
#define X_le_il_ok_button 244
#define X_le_il_cancel_button 245
#define X_le_il_select_button 246
#define X_le_il_help_button 247
#define X_le_il_description 248
#define X_le_il_spref 249
#define X_le_il_mpref 250
#define X_le_il_analysis_toggle 251
#define X_le_il_generation_toggle 252
#define X_le_il_angen_toggle 253
#define X_le_il_comments 254
#define X_le_il_mkey 255
#define X_le_il_modify_spref_button 256
#define X_le_il_modify_mpref_button 257
#define X_le_il_new_meaning_button 258
#define X_le_il_dutch_meaning_button 259
#define X_le_il_english_meaning_button 260
#define X_le_il_spanish_meaning_button 261
#define X_le_il_mark_il_button 262
#define X_le_il_delete_il_button 263
#define X_le_il_translate_dutch_button 264
#define X_le_il_translate_english_button 265
#define X_le_il_translate_spanish_button 266
#define X_le_il_status 267
#define X_le_sid_window 268
#define X_le_sid_ok_button 269
#define X_le_sid_cancel_button 270
#define X_le_sid_select_button 271
#define X_le_sid_help_button 272
#define X_le_sid_argument 273
#define X_le_sid_argnr 274
#define X_le_sid_comments 275
#define X_le_sid_skey 276
#define X_le_sid_mkey 277
#define X_le_sid_modify_argument_button 278
#define X_le_sid_modify_number_button 279
#define X_le_sid_new_meaning_button 280
#define X_le_sid_dutch_meaning_button 281
#define X_le_sid_english_meaning_button 282
#define X_le_sid_spanish_meaning_button 283
#define X_le_sid_delete_sid_button 284
#define X_le_sid_translate_dutch_button 285
#define X_le_sid_translate_english_button 286
#define X_le_sid_translate_spanish_button 287
#define X_le_sid_show_argument_button 288
#define X_le_sid_deleted 289
#define X_le_id_window 290
#define X_le_id_ok_button 291
#define X_le_id_cancel_button 292
#define X_le_id_select_button 293
#define X_le_id_help_button 294
#define X_le_id_arguments 295
#define X_le_id_pattern 296
#define X_le_id_comments 297
#define X_le_id_skey 298
#define X_le_id_mkey 299
#define X_le_id_modify_argument_button 300
#define X_le_id_modify_pattern_button 301
#define X_le_id_new_meaning_button 302
#define X_le_id_dutch_meaning_button 303
#define X_le_id_english_meaning_button 304
#define X_le_id_spanish_meaning_button 305
#define X_le_id_insert_argument_button 306
#define X_le_id_delete_id_button 307
#define X_le_id_translate_dutch_button 308
#define X_le_id_translate_english_button 309
#define X_le_id_translate_spanish_button 310
#define X_le_id_show_argument_button 311
#define X_le_id_deleted 312
#define X_le_error_window 313
#define X_le_error_ok_button 314
#define X_le_ask_string_window 315
#define X_le_ask_string_ok_button 316
#define X_le_ask_string_cancel_button 317
#define X_le_ask_string_prompt 318
#define X_le_ask_string_value 319
#define X_le_ask_boolean_window 320
#define X_le_ask_boolean_yes_button 321
#define X_le_ask_boolean_no_button 322
#define SCREEN_START 323
#define X_tree_window 323
#define X_tree_area 324
#define X_tree_ok_button 325
#define X_tree_expand_button 326
#define X_tree_orientation_button 327
#define X_tree_showtree_button 328
#define X_tree_help_button 329
#define X_trees_window 330
#define X_trees_area 331
#define X_trees_ok_button 332
#define X_trees_expand_button 333
#define X_trees_orientation_button 334
#define X_trees_showtree_button 335
#define X_trees_help_button 336
#define X_trees_card_text 337
#define X_trees_arity_text 338
#define X_trees_tuple_text 339
#define X_trees_stree_text 340
#define X_attr_window 341
#define X_attr_area 342
#define X_attr_ok_button 343
#define X_attr_tofile_button 344
#define X_attr_confirm_button 345
#define X_attr_help_button 346
#define X_hn_window 347
#define X_hn_area 348
#define X_hn_ok_button 349
#define X_hn_attr_button 350
#define X_hn_help_button 351
#define SCREEN_END 352
