#! /bin/sh
#
#
rm -f /home/rous/ipo/RBSversions/RBS1.6/RBS/*
#
chmod 777 /home/rous/RBSARCH/r4.2/script-sccs/*
chmod 777 /home/rous/RBSUSER/r4.2/script-sccs/source/*
#
#set -x
#set -v
#
cd /home/rous/RBSUSER/r4.2/script-sccs/source
for i in `ls`; do
    if ( test -f /home/rous/ipo/RBSversions/RBS1.6/RBS/$i )
    then echo "file $i already exists"
    else cp $i /home/rous/ipo/RBSversions/RBS1.6/RBS/$i
    fi
done
#
cd /home/rous/RBSARCH/r4.2/script-sccs
for i in `ls`; do
    if ( test -f /home/rous/ipo/RBSversions/RBS1.6/RBS/$i )
    then echo "link $i already exists"
    else cp $i /home/rous/ipo/RBSversions/RBS1.6/RBS/$i
    fi
done
#
#
cd /home/rous/RBSARCH/r4.2/bin-sunos
#
cp genmake.exe /home/rous/ipo/RBSversions/RBS1.6/RBS/genmake
cp get_fname.exe /home/rous/ipo/RBSversions/RBS1.6/RBS/get_fname
#
#
cd /home/rous/RBSUSER/r4.2/bin-sunos/target
if ( test -f genmake.exe )
then cp genmake.exe /home/rous/ipo/RBSversions/RBS1.6/RBS/genmake
fi
if ( test -f get_fname.exe )
then cp get_fname.exe /home/rous/ipo/RBSversions/RBS1.6/RBS/get_fname
fi
if ( test -f fuid.c )
then cp fuid.c /home/rous/ipo/RBSversions/RBS1.6/RBS/fuid.c
fi
#
#
