(*MPD:::===================================================================*
 *
 *  Rosetta Project
 *
 *  Module Title    : TldSTRtoSTR
 *  Creation date   :  10-JUN-1988
 *  Author          : Rene Leermakers
 *
 *  Copyright (c) 1986, by Nederlandse Philips Bedrijven BV.
 *
 *  Remarks         : The implementation corresponding to this definition
 *                    module is generated by the domain compiler
 *
 *EMP:::===================================================================*)
EXPORT(TLDSTRTOSTR);
pragma C_include('ldstrtostr.pf');
pragma C_include('tldstrtostr.pf');
pragma C_include('tstring.pf');
pragma C_include('string.pf');


PROGRAM TLDSTRTOSTR;
WITH ldstrtostr,tstring,strng;

 FUNCTION TldSTRtostr_CATtoRECTYPE(cat:TSTRING_string)
                    :TSTRING_string;
VAR str1,str2:STRING_string;
    str3:TSTRING_string;
BEGIN
TSTRING_converttostring(cat,str1);
str2:=ldSTRtoSTR_cattorectype(str1);
TSTRING_converttotstring(str2,str3);
TldSTRtoSTR_cattorectype:=str3
END;

 PROCEDURE TldSTRtostr_typeinfo(Typestr:TSTRING_string;
   VAR kind:INTEGER;VAR basetype,min,max:TSTRING_string);
VAR str1,str2,str3,str4:STRING_string;
BEGIN
TSTRING_converttostring(typestr,str1);
ldSTRtoSTR_typeinfo(str1,kind,str2,str3,str4);
TSTRING_converttotstring(str2,basetype);
TSTRING_converttotstring(str3,min);
TSTRING_converttotstring(str4,max);
END;

