EXPORT(genlexif);
pragma C_include('genlexif.pf');
pragma C_include('lsdomaint.pf');
pragma C_include('listree.pf');
pragma C_include('lidomaint.pf');
pragma C_include('mem.pf');
pragma C_include('decomlexrules1.pf');
pragma C_include('decomlexrules2.pf');
WITH genlexif;
pragma C_include('decomlexrules3.pf');
PROGRAM GENLEXIF;WITH lsdomaint,listree,lidomaint,mem,
decomlexrules1,decomlexrules2,decomlexrules3;

CONST
     maxrnr=141;
VAR licat:LIDOMAINT_syntcat;lscat:LSDOMAINT_syntcat;
   catarray:ARRAY[LIDOMAINT_syntcat] OF GENLEXIF_setofrules;

PROCEDURE MakePlosrule(VAR p:GENLEXIF_plosrule);
begin
MEM_NewDefault(LoopHoles.SIZEof(GENLEXIF_losrule),LoopHoles.Retype(p,Mem_Ptr));
end;
PROCEDURE initsetofrules(VAR S1:GENLEXIF_setofrules);
begin
S1.first:=nil;S1.last:=nil
end;
 FUNCTION GENLEXIF_stillrules(setofrules:GENLEXIF_setofrules):BOOLEAN;
begin
if setofrules.first<>nil then GENLEXIF_stillrules:=true
else GENLEXIF_stillrules:=false
end;
PROCEDURE appendrule(rule:GENLEXIF_lexruletype;VAR S1:GENLEXIF_setofrules);
VAR p:GENLEXIF_plosrule;
begin
makeplosrule(p);
p^.arg:=rule;
p^.next:=nil;
if S1.first=nil then
  begin
  S1.first:=p;
  S1.last:=p
  end
else
  begin
  S1.last^.next:=p;
  S1.last:=p
  end
end;
 PROCEDURE GENLEXIF_takerule(VAR rule:GENLEXIF_lexruletype;
                                       VAR setofRules:GENLEXIF_setofRules);
begin
if setofrules.first=nil then rule:=0
else
  begin
  rule:=setofrules.first^.arg;
  if setofrules.first=setofrules.last then
    begin
    setofrules.first:=nil;setofrules.last:=nil
    end
  else setofrules.first:=setofrules.first^.next
  end
end;
FUNCTION GENLEXIF_maxlexrulenr:INTEGER;
BEGIN
GENLEXIF_maxlexrulenr:=maxrnr
END;
 PROCEDURE GENLEXIF_init;
BEGIN
initsetofrules(catarray[licat1]);
initsetofrules(catarray[licat2]);
initsetofrules(catarray[licat3]);
initsetofrules(catarray[licat4]);
initsetofrules(catarray[licat5]);
initsetofrules(catarray[licat6]);
initsetofrules(catarray[licat7]);
initsetofrules(catarray[licat8]);
initsetofrules(catarray[licat9]);
initsetofrules(catarray[licat10]);
initsetofrules(catarray[licat11]);
initsetofrules(catarray[licat12]);
initsetofrules(catarray[licat13]);
initsetofrules(catarray[licat14]);
initsetofrules(catarray[licat15]);
initsetofrules(catarray[licat16]);
initsetofrules(catarray[licat17]);
initsetofrules(catarray[licat18]);
initsetofrules(catarray[licat19]);
initsetofrules(catarray[licat20]);
initsetofrules(catarray[licat21]);
initsetofrules(catarray[licat22]);
initsetofrules(catarray[licat23]);
initsetofrules(catarray[licat24]);
initsetofrules(catarray[licat25]);
initsetofrules(catarray[licat26]);
initsetofrules(catarray[licat27]);
initsetofrules(catarray[licat28]);
initsetofrules(catarray[licat29]);
initsetofrules(catarray[licat30]);
initsetofrules(catarray[licat31]);
initsetofrules(catarray[licat32]);
initsetofrules(catarray[licat33]);
initsetofrules(catarray[licat34]);
initsetofrules(catarray[licat35]);
initsetofrules(catarray[licat36]);
initsetofrules(catarray[licat37]);
initsetofrules(catarray[licat38]);
initsetofrules(catarray[licat39]);
initsetofrules(catarray[licat40]);
initsetofrules(catarray[licat41]);
initsetofrules(catarray[licat42]);
initsetofrules(catarray[licat43]);
initsetofrules(catarray[licat44]);
initsetofrules(catarray[licat45]);
initsetofrules(catarray[licat46]);
initsetofrules(catarray[licat47]);
initsetofrules(catarray[licat48]);
initsetofrules(catarray[licat49]);
initsetofrules(catarray[licat50]);
initsetofrules(catarray[licat51]);
initsetofrules(catarray[licat52]);
initsetofrules(catarray[licat53]);
initsetofrules(catarray[licat54]);
initsetofrules(catarray[licat55]);
initsetofrules(catarray[licat56]);
initsetofrules(catarray[licat57]);
initsetofrules(catarray[licat58]);
initsetofrules(catarray[licat59]);
initsetofrules(catarray[licat60]);
initsetofrules(catarray[licat61]);
initsetofrules(catarray[licat62]);
initsetofrules(catarray[licat63]);
initsetofrules(catarray[licat64]);
initsetofrules(catarray[licat65]);
initsetofrules(catarray[licat66]);
initsetofrules(catarray[licat67]);
initsetofrules(catarray[licat68]);
initsetofrules(catarray[licat69]);
initsetofrules(catarray[licat70]);
initsetofrules(catarray[licat71]);
initsetofrules(catarray[licat72]);
initsetofrules(catarray[licat73]);
initsetofrules(catarray[licat74]);
initsetofrules(catarray[licat75]);
initsetofrules(catarray[licat76]);
initsetofrules(catarray[licat77]);
initsetofrules(catarray[licat78]);
initsetofrules(catarray[licat79]);
initsetofrules(catarray[licat80]);
initsetofrules(catarray[licat81]);
initsetofrules(catarray[licat82]);
initsetofrules(catarray[licat83]);
initsetofrules(catarray[licat84]);
initsetofrules(catarray[licat85]);
initsetofrules(catarray[licat86]);
initsetofrules(catarray[licat87]);
initsetofrules(catarray[licat88]);
initsetofrules(catarray[licat89]);
initsetofrules(catarray[licat90]);
initsetofrules(catarray[licat91]);
initsetofrules(catarray[licat92]);
initsetofrules(catarray[licat93]);
initsetofrules(catarray[licat94]);
initsetofrules(catarray[licat95]);
initsetofrules(catarray[licat96]);
initsetofrules(catarray[licat97]);
initsetofrules(catarray[licat98]);
initsetofrules(catarray[licat99]);
initsetofrules(catarray[licat100]);
initsetofrules(catarray[licat101]);
initsetofrules(catarray[licat102]);
initsetofrules(catarray[licat103]);
initsetofrules(catarray[licat104]);
initsetofrules(catarray[licat105]);
initsetofrules(catarray[licat106]);
initsetofrules(catarray[licat107]);
initsetofrules(catarray[licat108]);
initsetofrules(catarray[licat109]);
initsetofrules(catarray[licat110]);
initsetofrules(catarray[licat111]);
initsetofrules(catarray[licat112]);
initsetofrules(catarray[licat113]);
initsetofrules(catarray[licat114]);
initsetofrules(catarray[licat115]);
initsetofrules(catarray[licat116]);
initsetofrules(catarray[licat117]);
initsetofrules(catarray[licat118]);
initsetofrules(catarray[licat119]);
initsetofrules(catarray[licat120]);
initsetofrules(catarray[licat121]);
initsetofrules(catarray[licat122]);
initsetofrules(catarray[licat123]);
initsetofrules(catarray[licat124]);
initsetofrules(catarray[licat125]);
initsetofrules(catarray[licat126]);
initsetofrules(catarray[licat127]);
initsetofrules(catarray[licat128]);
initsetofrules(catarray[licat129]);
initsetofrules(catarray[licat130]);
initsetofrules(catarray[licat131]);
initsetofrules(catarray[licat132]);
initsetofrules(catarray[licat133]);
initsetofrules(catarray[licat134]);
initsetofrules(catarray[licat135]);
initsetofrules(catarray[licat136]);
initsetofrules(catarray[licat137]);
initsetofrules(catarray[licat138]);
initsetofrules(catarray[licat139]);
initsetofrules(catarray[licat140]);
initsetofrules(catarray[licat141]);
initsetofrules(catarray[licat142]);
initsetofrules(catarray[licat143]);
initsetofrules(catarray[licat144]);
initsetofrules(catarray[licat145]);
initsetofrules(catarray[licat146]);
initsetofrules(catarray[licat147]);
initsetofrules(catarray[licat148]);
initsetofrules(catarray[licat149]);
initsetofrules(catarray[licat150]);
lscat:=SUBADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(118,catarray[licat]);
lscat:=SUBADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(141,catarray[licat]);
lscat:=ADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(113,catarray[licat]);
lscat:=ADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(114,catarray[licat]);
lscat:=ADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(115,catarray[licat]);
lscat:=ADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(116,catarray[licat]);
lscat:=ADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(117,catarray[licat]);
lscat:=SUBADV;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(120,catarray[licat]);
lscat:=SUBADV;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(121,catarray[licat]);
lscat:=ADV;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(119,catarray[licat]);
lscat:=DEMADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(132,catarray[licat]);
lscat:=DEMADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(133,catarray[licat]);
lscat:=DET;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(137,catarray[licat]);
lscat:=DET;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(138,catarray[licat]);
lscat:=CARD;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(139,catarray[licat]);
lscat:=CARD;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(140,catarray[licat]);
lscat:=SUBNOUN;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(112,catarray[licat]);
lscat:=NOUN;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(109,catarray[licat]);
lscat:=NOUN;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(110,catarray[licat]);
lscat:=NOUN;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(111,catarray[licat]);
lscat:=PERSPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(122,catarray[licat]);
lscat:=PERSPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(123,catarray[licat]);
lscat:=PERSPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(124,catarray[licat]);
lscat:=PERSPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(125,catarray[licat]);
lscat:=PERSPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(126,catarray[licat]);
lscat:=POSSADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(127,catarray[licat]);
lscat:=POSSADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(128,catarray[licat]);
lscat:=POSSPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(129,catarray[licat]);
lscat:=POSSPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(130,catarray[licat]);
lscat:=POSSPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(131,catarray[licat]);
lscat:=PROPERNOUN;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(135,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(75,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(76,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(77,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(78,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(79,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(80,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(81,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(82,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(83,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(84,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(85,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(86,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(87,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(88,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(89,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(90,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(91,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(92,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(93,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(94,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(95,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(96,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(97,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(98,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(99,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(100,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(101,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(102,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(103,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(104,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(105,catarray[licat]);
lscat:=ALOVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(106,catarray[licat]);
lscat:=SUBVERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(108,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(1,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(2,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(3,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(4,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(5,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(6,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(7,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(8,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(9,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(10,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(11,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(12,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(13,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(14,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(15,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(16,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(17,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(18,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(19,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(20,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(21,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(22,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(23,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(24,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(25,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(26,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(27,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(28,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(29,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(30,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(31,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(32,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(33,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(34,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(35,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(36,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(37,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(38,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(39,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(40,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(41,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(42,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(43,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(44,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(45,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(46,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(47,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(48,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(49,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(50,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(51,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(52,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(53,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(54,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(55,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(56,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(57,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(58,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(59,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(60,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(61,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(62,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(63,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(64,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(65,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(66,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(67,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(68,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(69,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(70,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(71,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(72,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(73,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(74,catarray[licat]);
lscat:=VERB;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(107,catarray[licat]);
lscat:=WHADJ;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(134,catarray[licat]);
lscat:=WHPRO;licat:=LoopHoles.Retype(lscat,LIDOMAINT_syntcat);appendrule(136,catarray[licat]);
END;
 FUNCTION GENLEXIF_switch(t:LISTREE_pstree)
:GENLEXIF_setofRules;
BEGIN
GENLEXIF_switch:=catarray[t^.cat]
END;
 FUNCTION GENLEXIF_lexrule(L:GENLEXIF_lexruletype;
                                    t:LISTREE_pstree)
                : LISTREE_setoftupleofstrees;
BEGIN
CASE L of
1: GENLEXIF_lexrule:= decPtcpasSG(t);
2: GENLEXIF_lexrule:= decPtcpasPL(t);
3: GENLEXIF_lexrule:= decGerundio(t);
4: GENLEXIF_lexrule:= decPresIndSG1(t);
5: GENLEXIF_lexrule:= decPresSubjSG1(t);
6: GENLEXIF_lexrule:= decImperfSG1(t);
7: GENLEXIF_lexrule:= decPDsg1(t);
8: GENLEXIF_lexrule:= decSubjPasSG1(t);
9: GENLEXIF_lexrule:= decSubjPasaSG1(t);
10: GENLEXIF_lexrule:= decFuturoSG1(t);
11: GENLEXIF_lexrule:= decCondicSG1(t);
12: GENLEXIF_lexrule:= decPresIndSG2(t);
13: GENLEXIF_lexrule:= decPresSubjSG2(t);
14: GENLEXIF_lexrule:= decImperfSG2(t);
15: GENLEXIF_lexrule:= decPDsg2(t);
16: GENLEXIF_lexrule:= decSubjPasSG2(t);
17: GENLEXIF_lexrule:= decSubjPasaSG2(t);
18: GENLEXIF_lexrule:= decFuturoSG2(t);
19: GENLEXIF_lexrule:= decCondicSG2(t);
20: GENLEXIF_lexrule:= decImperatSG(t);
21: GENLEXIF_lexrule:= decPresIndSG3(t);
22: GENLEXIF_lexrule:= decPresSubjSG3(t);
23: GENLEXIF_lexrule:= decImperfSG3(t);
24: GENLEXIF_lexrule:= decPDsg3(t);
25: GENLEXIF_lexrule:= decSubjPasSG3(t);
26: GENLEXIF_lexrule:= decSubjPasaSG3(t);
27: GENLEXIF_lexrule:= decFuturoSG3(t);
28: GENLEXIF_lexrule:= decCondicSG3(t);
29: GENLEXIF_lexrule:= decPresIndPL1(t);
30: GENLEXIF_lexrule:= decPresSubjPL1(t);
31: GENLEXIF_lexrule:= decImperfPL1(t);
32: GENLEXIF_lexrule:= decPDpl1(t);
33: GENLEXIF_lexrule:= decSubjPasPL1(t);
34: GENLEXIF_lexrule:= decSubjPasaPL1(t);
35: GENLEXIF_lexrule:= decFuturoPL1(t);
36: GENLEXIF_lexrule:= decCondicPL1(t);
37: GENLEXIF_lexrule:= decPresIndPL2(t);
38: GENLEXIF_lexrule:= decPresSubjPL2(t);
39: GENLEXIF_lexrule:= decImperfPL2(t);
40: GENLEXIF_lexrule:= decPDpl2(t);
41: GENLEXIF_lexrule:= decSubjPasPL2(t);
42: GENLEXIF_lexrule:= decSubjPasaPL2(t);
43: GENLEXIF_lexrule:= decFuturoPL2(t);
44: GENLEXIF_lexrule:= decCondicPL2(t);
45: GENLEXIF_lexrule:= decImperatPL(t);
46: GENLEXIF_lexrule:= decPresIndPL3(t);
47: GENLEXIF_lexrule:= decPresSubjPL3(t);
48: GENLEXIF_lexrule:= decImperfPL3(t);
49: GENLEXIF_lexrule:= decPDpl3(t);
50: GENLEXIF_lexrule:= decSubjPasPL3(t);
51: GENLEXIF_lexrule:= decSubjPasaPL3(t);
52: GENLEXIF_lexrule:= decFuturoPL3(t);
53: GENLEXIF_lexrule:= decCondicPL3(t);
54: GENLEXIF_lexrule:= decInfinitivo(t);
55: GENLEXIF_lexrule:= decInfIRR(t);
56: GENLEXIF_lexrule:= decPtcpasIRR(t);
57: GENLEXIF_lexrule:= decGerundioIRR(t);
58: GENLEXIF_lexrule:= decPresIndIRRsg(t);
59: GENLEXIF_lexrule:= decPresIndIRRpl(t);
60: GENLEXIF_lexrule:= decPresSubjIRRsg(t);
61: GENLEXIF_lexrule:= decPresSubjIRRpl(t);
62: GENLEXIF_lexrule:= decImperfIRRsg(t);
63: GENLEXIF_lexrule:= decImperfIRRpl(t);
64: GENLEXIF_lexrule:= decPDirrSG(t);
65: GENLEXIF_lexrule:= decPDirrPL(t);
66: GENLEXIF_lexrule:= decSubjPasIRRsg(t);
67: GENLEXIF_lexrule:= decSubjPasIRRpl(t);
68: GENLEXIF_lexrule:= decSubjPasaIRRsg(t);
69: GENLEXIF_lexrule:= decSubjPasaIRRpl(t);
70: GENLEXIF_lexrule:= decFuturoIRRsg(t);
71: GENLEXIF_lexrule:= decFuturoIRRpl(t);
72: GENLEXIF_lexrule:= decCondIRRsg(t);
73: GENLEXIF_lexrule:= decCondIRRpl(t);
74: GENLEXIF_lexrule:= decImperatIRR(t);
75: GENLEXIF_lexrule:= decALOSUBnadadiftong(t);
76: GENLEXIF_lexrule:= decALOSUBirrMedek(t);
77: GENLEXIF_lexrule:= decALOSUBsterk(t);
78: GENLEXIF_lexrule:= decALOSUBeiouHalf(t);
79: GENLEXIF_lexrule:= decALOSUBeiouHeel(t);
80: GENLEXIF_lexrule:= decALOSUByMinPres(t);
81: GENLEXIF_lexrule:= decALOSUBumlaut(t);
82: GENLEXIF_lexrule:= decALOSUBve(t);
83: GENLEXIF_lexrule:= decALOSUBirrMedek_sterk(t);
84: GENLEXIF_lexrule:= decALOSUBdiftong_eiouHalf(t);
85: GENLEXIF_lexrule:= decPresIndALOsg1(t);
86: GENLEXIF_lexrule:= decPresIndALOsg23(t);
87: GENLEXIF_lexrule:= decPresIndALOpl3(t);
88: GENLEXIF_lexrule:= decPresSubjALOsg123(t);
89: GENLEXIF_lexrule:= decPresSubjALOpl1(t);
90: GENLEXIF_lexrule:= decPresSubjALOpl2(t);
91: GENLEXIF_lexrule:= decPresSubjALOpl3(t);
92: GENLEXIF_lexrule:= decImperatALOsg(t);
93: GENLEXIF_lexrule:= decSubjPasALOsg1(t);
94: GENLEXIF_lexrule:= decSubjPasALOsg2(t);
95: GENLEXIF_lexrule:= decSubjPasALOsg3(t);
96: GENLEXIF_lexrule:= decSubjPasALOpl1(t);
97: GENLEXIF_lexrule:= decSubjPasALOpl2(t);
98: GENLEXIF_lexrule:= decSubjPasALOpl3(t);
99: GENLEXIF_lexrule:= decPDaloSG1(t);
100: GENLEXIF_lexrule:= decPDaloSG2(t);
101: GENLEXIF_lexrule:= decPDaloSG3(t);
102: GENLEXIF_lexrule:= decPDaloPL1(t);
103: GENLEXIF_lexrule:= decPDaloPL2(t);
104: GENLEXIF_lexrule:= decPDaloPL3(t);
105: GENLEXIF_lexrule:= decGerundioALO(t);
106: GENLEXIF_lexrule:= decImperfALO(t);
107: GENLEXIF_lexrule:= decIRRPtcpas(t);
108: GENLEXIF_lexrule:= decSUBBASICverb(t);
109: GENLEXIF_lexrule:= decNOUNsg(t);
110: GENLEXIF_lexrule:= decsincambioNOUNpl(t);
111: GENLEXIF_lexrule:= deccambioNOUNpl(t);
112: GENLEXIF_lexrule:= decSUBBASICnoun(t);
113: GENLEXIF_lexrule:= decADJsgNOCAMBIO(t);
114: GENLEXIF_lexrule:= decADJsgCAMBIOfem(t);
115: GENLEXIF_lexrule:= decADJsgCAMBIOmasc(t);
116: GENLEXIF_lexrule:= decApocopeADJ(t);
117: GENLEXIF_lexrule:= decADJpl(t);
118: GENLEXIF_lexrule:= decSUBBASICadj(t);
119: GENLEXIF_lexrule:= decADVSUBadv(t);
120: GENLEXIF_lexrule:= decSUBBASICadv(t);
121: GENLEXIF_lexrule:= decAdjToAdvDerivMENTE(t);
122: GENLEXIF_lexrule:= decDOclitics(t);
123: GENLEXIF_lexrule:= decIOclitics(t);
124: GENLEXIF_lexrule:= decPrepPronFuerte(t);
125: GENLEXIF_lexrule:= decPronNomfuerte(t);
126: GENLEXIF_lexrule:= decPronPrepfuerte(t);
127: GENLEXIF_lexrule:= decposADJsg(t);
128: GENLEXIF_lexrule:= decposADJpl(t);
129: GENLEXIF_lexrule:= decposPROsg(t);
130: GENLEXIF_lexrule:= decposPROsgFEM(t);
131: GENLEXIF_lexrule:= decposPROplur(t);
132: GENLEXIF_lexrule:= decDemAdj(t);
133: GENLEXIF_lexrule:= decDemAdjMascSing(t);
134: GENLEXIF_lexrule:= decWhADJ(t);
135: GENLEXIF_lexrule:= decProperTObpropernoun(t);
136: GENLEXIF_lexrule:= decWHPROtoBWHPRO(t);
137: GENLEXIF_lexrule:= decDETflection(t);
138: GENLEXIF_lexrule:= decDETnoflection(t);
139: GENLEXIF_lexrule:= decCARDrule1(t);
140: GENLEXIF_lexrule:= decCARDrule2(t);
141: GENLEXIF_lexrule:= decCardTOord(t);
END;
END;
