Export(LDCATSETS);
pragma C_include('lidomaint.pf');
pragma C_include('ldcatsets.pf');
PROGRAM LDCATSETS;
WITH LIDOMAINT;
FUNCTION LDCATSETS_UTTERANCE(cat:LIDOMAINT_syntcat):BOOLEAN;
VAR catset:SET OF LIDOMAINT_syntcat;
BEGIN
catset:=[
LICAT83
  ];
IF cat in catset THEN LDCATSETS_UTTERANCE:=TRUE
ELSE LDCATSETS_UTTERANCE:=FALSE
END;
FUNCTION LDCATSETS_TOPCAT(cat:LIDOMAINT_syntcat):BOOLEAN;
VAR catset:SET OF LIDOMAINT_syntcat;
BEGIN
catset:=[
LICAT5
,LICAT14
,LICAT31
,LICAT46
,LICAT47
,LICAT65
,LICAT76
,LICAT80
,LICAT82
,LICAT83
,LICAT101
,LICAT102
  ];
IF cat in catset THEN LDCATSETS_TOPCAT:=TRUE
ELSE LDCATSETS_TOPCAT:=FALSE
END;
FUNCTION LDCATSETS_LEXCAT(cat:LIDOMAINT_syntcat):BOOLEAN;
VAR catset:SET OF LIDOMAINT_syntcat;
BEGIN
catset:=[
LICAT4
,LICAT13
,LICAT20
,LICAT24
,LICAT25
,LICAT27
,LICAT28
,LICAT30
,LICAT35
,LICAT113
,LICAT36
,LICAT38
,LICAT45
,LICAT53
,LICAT54
,LICAT56
,LICAT58
,LICAT60
,LICAT62
,LICAT64
,LICAT72
,LICAT74
,LICAT75
,LICAT78
,LICAT79
,LICAT81
,LICAT101
,LICAT108
,LICAT110
,LICAT41
  ];
IF cat in catset THEN LDCATSETS_LEXCAT:=TRUE
ELSE LDCATSETS_LEXCAT:=FALSE
END;
FUNCTION LDCATSETS_BLEXCAT(cat:LIDOMAINT_syntcat):BOOLEAN;
VAR catset:SET OF LIDOMAINT_syntcat;
BEGIN
catset:=[
LICAT1
,LICAT2
,LICAT10
,LICAT11
,LICAT21
,LICAT24
,LICAT25
,LICAT26
,LICAT28
,LICAT29
,LICAT34
,LICAT32
,LICAT33
,LICAT35
,LICAT36
,LICAT38
,LICAT42
,LICAT43
,LICAT53
,LICAT54
,LICAT55
,LICAT58
,LICAT64
,LICAT71
,LICAT74
,LICAT75
,LICAT97
,LICAT98
,LICAT107
,LICAT109
,LICAT40
,LICAT20
,LICAT113
,LICAT78
,LICAT77
,LICAT79
,LICAT81
  ];
IF cat in catset THEN LDCATSETS_BLEXCAT:=TRUE
ELSE LDCATSETS_BLEXCAT:=FALSE
END;
FUNCTION LDCATSETS_VARCATSET(cat:LIDOMAINT_syntcat):BOOLEAN;
VAR catset:SET OF LIDOMAINT_syntcat;
BEGIN
catset:=[
LICAT84
,LICAT85
,LICAT86
,LICAT88
,LICAT90
,LICAT87
,LICAT91
,LICAT96
,LICAT93
,LICAT92
,LICAT94
,LICAT95
,LICAT89
,LICAT15
  ];
IF cat in catset THEN LDCATSETS_VARCATSET:=TRUE
ELSE LDCATSETS_VARCATSET:=FALSE
END;
FUNCTION LDCATSETS_SUFFIXCAT(cat:LIDOMAINT_syntcat):BOOLEAN;
VAR catset:SET OF LIDOMAINT_syntcat;
BEGIN
catset:=[
LICAT1
,LICAT10
,LICAT42
,LICAT97
  ];
IF cat in catset THEN LDCATSETS_SUFFIXCAT:=TRUE
ELSE LDCATSETS_SUFFIXCAT:=FALSE
END;
FUNCTION LDCATSETS_PREFIXCAT(cat:LIDOMAINT_syntcat):BOOLEAN;
VAR catset:SET OF LIDOMAINT_syntcat;
BEGIN
catset:=[
  ];
IF cat in catset THEN LDCATSETS_PREFIXCAT:=TRUE
ELSE LDCATSETS_PREFIXCAT:=FALSE
END;
