#! /bin/sh
d=$RBS_ARCHIVE$RBS_RELEASE/dutch
e=$RBS_ARCHIVE$RBS_RELEASE/english
s=$RBS_ARCHIVE$RBS_RELEASE/spanish
t=/home/uittenbo/0/rosetta3/tools/target
# t=$RBS_ARCHIVE$RBS_RELEASE/tools
echo "lockedlemmas /home/rosetta/archive/rosetta3/dutch/lexedlock.dat" > lognames 
$t/lockinit.exe lognames
echo "lockedlemmas /home/rosetta/archive/rosetta3/english/lexedlock.dat" > lognames 
$t/lockinit.exe lognames
echo "lockedlemmas /home/rosetta/archive/rosetta3/spanish/lexedlock.dat" > lognames 
$t/lockinit.exe lognames
