#! /bin/sh -e
trap 'echo "opt: Error during linking" ; exit 1' 0
echo "opt: $1:$2"
actecute mopt $1 $2
rm -f linkfile
echo "#! /bin/sh -e" > linkfile
echo "pp -o $1/target/$2.exe \\" >> linkfile
if test -s $1/target/$2.opt
then cat $1/target/$2.opt >> linkfile
else cat $RBS_ARCHIVE$RBS_RELEASE/$1/$2.opt >> linkfile
fi
echo "1>> warnings 2>&1" >> linkfile
chmod u+x linkfile
echo "  "  >> warnings
linkfile
trap 0
