#! /bin/sh -e
trap 'echo "pas: Error during compilation" ; exit 1' 0
        echo "  " >> warnings
        echo "pas: $1:$2"
        if test -s $1/source/$2.p 
        then 
             if ( test "$3" = "dutch") || \
                ( test "$3" = "english") || \
                ( test "$3" = "spanish")
             then if test -s $2.o
                  then  rm -f $2.o
	          fi
                  pp -c -w -Hpro=$RBS_ARCHIVE$RBS_RELEASE/actions/pp.pro \
                      -I$3/source -I$3/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/$3 \
                      -Iunix/source -Iunix/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/unix \
                      -Igeneral/source -Igeneral/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/general \
                      -Ivms/source -Ivms/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/vms \
                      -Itools/source -Itools/target  \
                      -I$RBS_ARCHIVE$RBS_RELEASE/tools \
                      -Iinterlingua/source -Iinterlingua/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/interlingua \
                      -IXw/source -IXw/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/Xw \
                      $1/source/$2.p 1>> warnings 2>&1
	          if test -s $2.o 
                  then rm -f $3/target/$2.o
	               mv $2.o $3/target/$2.o
	          fi
             else if test -s $2.o
                  then  rm -f $2.o
	          fi
                  if ( test "$1" = "dutch") || (test "$1" = "english") || \
                      (test "$1" = "spanish") 
                  then pp -c -w -Hpro=$RBS_ARCHIVE$RBS_RELEASE/actions/pp.pro \
                      -I$1/source -I$1/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/$1 \
                      -Iunix/source -Iunix/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/unix \
                      -Igeneral/source -Igeneral/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/general \
                      -Ivms/source -Ivms/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/vms \
                      -Itools/source -Itools/target  \
                      -I$RBS_ARCHIVE$RBS_RELEASE/tools \
                      -Iinterlingua/source -Iinterlingua/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/interlingua \
                      -IXw/source -IXw/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/Xw \
                      $1/source/$2.p 1>> warnings 2>&1
                  else pp -c -w -Hpro=$RBS_ARCHIVE$RBS_RELEASE/actions/pp.pro \
                      -Iunix/source -Iunix/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/unix \
                      -Igeneral/source -Igeneral/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/general \
                      -Ivms/source -Ivms/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/vms \
                      -Itools/source -Itools/target  \
                      -I$RBS_ARCHIVE$RBS_RELEASE/tools \
                      -Iinterlingua/source -Iinterlingua/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/interlingua \
                      -IXw/source -IXw/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/Xw \
                      $1/source/$2.p 1>> warnings 2>&1
                  fi
	          if test -s $2.o 
                  then rm -f $1/target/$2.o
	               mv $2.o $1/target/$2.o
	          fi
             fi
        elif ( test -s $1/target/$2.p ) then
             if test -s $2.o
             then  rm -f $2.o
	     fi
             if ( test "$1" = "dutch") || (test "$1" = "english") || (test "$1" = "spanish") 
             then pp -c -w -Hpro=$RBS_ARCHIVE$RBS_RELEASE/actions/pp.pro \
                      -I$1/source -I$1/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/$1 \
                      -Iunix/source -Iunix/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/unix \
                      -Igeneral/source -Igeneral/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/general \
                      -Ivms/source -Ivms/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/vms \
                      -Itools/source -Itools/target  \
                      -I$RBS_ARCHIVE$RBS_RELEASE/tools \
                      -Iinterlingua/source -Iinterlingua/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/interlingua \
                      -IXw/source -IXw/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/Xw \
                      $1/target/$2.p 1>> warnings 2>&1
             else pp -c -w -Hpro=$RBS_ARCHIVE$RBS_RELEASE/actions/pp.pro \
                      -Iunix/source -Iunix/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/unix \
                      -Igeneral/source -Igeneral/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/general \
                      -Ivms/source -Ivms/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/vms \
                      -Itools/source -Itools/target  \
                      -I$RBS_ARCHIVE$RBS_RELEASE/tools \
                      -Iinterlingua/source -Iinterlingua/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/interlingua \
                      -IXw/source -IXw/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/Xw \
                      $1/target/$2.p 1>> warnings 2>&1
             fi
	     if test -s $2.o 
             then rm -f $1/target/$2.o
	          mv $2.o $1/target/$2.o
	     fi
        elif ( test -s $RBS_ARCHIVE$RBS_RELEASE/$1/$2.p ) then
             if ( test "$3" = "dutch") || \
                ( test "$3" = "english") || \
                ( test "$3" = "spanish")
             then if test -s $2.o
                  then  rm -f $2.o
	          fi
                  pp -c -w -Hpro=$RBS_ARCHIVE$RBS_RELEASE/actions/pp.pro \
                      -I$3/source -I$3/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/$3 \
                      -Iunix/source -Iunix/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/unix \
                      -Igeneral/source -Igeneral/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/general \
                      -Ivms/source -Ivms/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/vms \
                      -Itools/source -Itools/target  \
                      -I$RBS_ARCHIVE$RBS_RELEASE/tools \
                      -Iinterlingua/source -Iinterlingua/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/interlingua \
                      -IXw/source -IXw/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/Xw \
                      $RBS_ARCHIVE$RBS_RELEASE/$1/$2.p 1>> warnings 2>&1
	          if test -s $2.o 
                  then rm -f $3/target/$2.o
	               mv $2.o $3/target/$2.o
	          fi
             else if test -s $2.o
                  then  rm -f $2.o
	          fi
                  if ( test "$1" = "dutch") || (test "$1" = "english") || \
                      (test "$1" = "spanish") 
                  then pp -c -w -Hpro=$RBS_ARCHIVE$RBS_RELEASE/actions/pp.pro \
                      -I$1/source -I$1/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/$1 \
                      -Iunix/source -Iunix/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/unix \
                      -Igeneral/source -Igeneral/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/general \
                      -Ivms/source -Ivms/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/vms \
                      -Itools/source -Itools/target  \
                      -I$RBS_ARCHIVE$RBS_RELEASE/tools \
                      -Iinterlingua/source -Iinterlingua/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/interlingua \
                      -IXw/source -IXw/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/Xw \
                      $RBS_ARCHIVE$RBS_RELEASE/$1/$2.p 1>> warnings 2>&1
                  else pp -c -w -Hpro=$RBS_ARCHIVE$RBS_RELEASE/actions/pp.pro \
                      -Iunix/source -Iunix/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/unix \
                      -Igeneral/source -Igeneral/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/general \
                      -Ivms/source -Ivms/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/vms \
                      -Itools/source -Itools/target  \
                      -I$RBS_ARCHIVE$RBS_RELEASE/tools \
                      -Iinterlingua/source -Iinterlingua/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/interlingua \
                      -IXw/source -IXw/target \
                      -I$RBS_ARCHIVE$RBS_RELEASE/Xw \
                      $RBS_ARCHIVE$RBS_RELEASE/$1/$2.p 1>> warnings 2>&1
                  fi
	          if test -s $2.o 
                  then rm -f $1/target/$2.o
	               mv $2.o $1/target/$2.o
	          fi
             fi
 
        fi
trap 0
