#! /bin/sh -e
trap 'echo "stripdef: Error during stripdef" ; exit 1' 0
echo "  " >> warnings
echo "stripdef: $1:$2"
if test -s $1/source/$2.def
then
  src=$1/source/$2.def
else
  src=$RBS_ARCHIVE$RBS_RELEASE/$1/$2.def
fi

stripdef < $src > $1/target/$2.h

trap 0

 
