#! /bin/sh -e
trap 'echo "uid: Error during compilation" ; exit 1' 0
echo "  " >> warnings
echo "uid: $1:$2"
if test -s $1/source/$2.uil
then
  src=$1/source/$2.uil
else
  src=$RBS_ARCHIVE$RBS_RELEASE/$1/$2.uil
fi

/lib/cpp  -P -I$1/source -I$1/target -I$RBS_ARCHIVE$RBS_RELEASE/$1 $src > /tmp/$2.uil
/cadappl/X11/usr/bin/X11/uil -o $1/target/$2.uid /tmp/$2.uil 1>> warnings 2>&1
rm -f /tmp/$2.uil

trap 0
 
