#! /bin/sh -e
#
case $# in
0) echo "Usage: dgold filename version"; exit 1;;
1) echo "Usage: dgold filename version"; exit 1;;
2) ;;
*) echo "Usage: dgold filename version"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
#
#
#
trap '' 1 2 3
#
#
set -e
trap 'echo "DGOLD: No dgold allowed during your integrate"; cd $savedir; exit 2' 0
if ( test -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/integrate.rbs )
then exit 0
fi
#
#
set -e 
trap 'echo "DGOLD: Error during dgold" ; cd $savedir ; exit 2' 0
#
#
#
cd $HOME
sccs -d$RBS_ARCHIVE$RBS_RELEASE/doc -psccs get -k -r$2 $1.ascii
uudecode $1.ascii
rm -f $1.ascii
#
echo "DGOLD: file $1 in your HOME directory"
#
cd $savedir
trap 0
 
