#! /bin/sh -e
#
case $# in
0) echo "Usage: gold componentname filename version"; exit 1;;
1) echo "Usage: gold componentname filename version"; exit 1;;
2) echo "Usage: gold componentname filename version"; exit 1;;
3) ;;
*) echo "Usage: gold componentname filename version"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
#
#
#
trap '' 1 2 3
#
#
set -e
trap 'echo "GOLD: No gold allowed during your integrate"; cd $savedir; exit 2' 0
if ( test -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/integrate.rbs )
then exit 0
fi
#
#
set -e 
trap 'echo "GOLD: Error during gold" ; cd $savedir ; exit 2' 0
#
#
#
cd $HOME
sccs -d$RBS_ARCHIVE$RBS_RELEASE/$1 -psccs get -k -r$3 $2
#
echo "GOLD: file $2 in your HOME directory"
#
cd $savedir
trap 0
