#! /bin/sh -e
#
case $# in
0) echo "Usage: grodify componentname filename [path]"; exit 1;;
1) echo "Usage: grodify componentname filename [path]"; exit 1;;
2) ;;
3) ;;
*) echo "Usage: grodify componentname filename [path]"; exit 1;;
esac 
grab $1 $2 $3
modify $1 $2
#
exit
