#! /bin/sh -e
#
case $# in
0) echo "Usage: tosave componentname filename"; exit 1;;
1) echo "Usage: tosave componentname filename"; exit 1;;
2) ;;
*) echo "Usage: tosave componentname filename"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/$1
# 
if ( test -s $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/lock.rbs ) 
then echo "WARNING: You are building, do you want me to continue ? (y/n)"
     read x
     if ( test "$x" = "y" ) 
     then mv source/$2 save
     fi 
else mv source/$2 save
fi
#
cd $savedir
