BUILD: build started at Mon Nov  4 21:55:48 MET 1996
MAKE: Generating new makefiles......
BUILD: inspecting make file.....
ccrbs: src to bin-sunos genmake nodebug
ccrbs: compiling: src/source/genmake.c
lrbs: bin-sunos:genmake
BUILD: build completed at Mon Nov  4 21:55:52 MET 1996
 
