INTEGRATE: integrate started at Thu Apr 10 11:04:00 MET DST 1997!
CLEAR: clearing directory actions
CLEAR: clearing directory arch/source
CLEAR: clearing directory arch/target
CLEAR: clearing directory bin-hp/source
CLEAR: clearing directory bin-hp/target
CLEAR: clearing directory bin-mac/source
CLEAR: clearing directory bin-mac/target
CLEAR: clearing directory bin-pc/source
CLEAR: clearing directory bin-pc/target
CLEAR: clearing directory bin-sgi/source
CLEAR: clearing directory bin-sgi/target
CLEAR: clearing directory bin-solaris/source
CLEAR: clearing directory bin-solaris/target
CLEAR: clearing directory bin-sunos/source
CLEAR: clearing directory bin-sunos/target
CLEAR: skipping component doc
CLEAR: clearing directory mk/source
CLEAR: clearing directory mk/target
CLEAR: clearing directory script/source
CLEAR: clearing directory script/target
CLEAR: clearing directory script-rcs/source
CLEAR: clearing directory script-rcs/target
CLEAR: clearing directory script-sccs/source
CLEAR: clearing directory script-sccs/target
CLEAR: clearing directory src/source
CLEAR: clearing directory src/target
CLEAR: removing file src.make.rbs
CLEAR: Cleaning up finished
INTEGRATE: build actions started at Thu Apr 10 11:04:06 MET DST 1997!
INTEGRATE: Error during build
