========INTEGRATION HISTORY===========
rous: Tue Oct 17 11:26:34 MET 1995
    fisrt integration
rous: Tue Oct 17 11:48:15 MET 1995
    created rgrab
rous: Tue Oct 17 11:51:21 MET 1995
    testing rgrab
rous: Wed Oct 18 14:06:43 MET 1995
    added the platform specific component feature
rous: Wed Oct 18 16:03:37 MET 1995
    added debug feature
rous: Wed Oct 18 17:20:17 MET 1995
    added addcomponent install_component, dshold and dgold
rous: Mon Oct 23 16:09:18 MET 1995
    added path expansion in actions part of dependency in genmake.c
rous: Thu Oct 26 16:10:27 MET 1995
    repaired sending mail in integrate command
rous: Mon Nov  6 11:22:14 MET 1995
    repaired sending mail in integrate command
rous: Mon Nov  6 11:33:36 MET 1995
    
rous: Mon Nov  6 11:35:08 MET 1995
    repaired sending mail in integrate command
rous: Mon Nov  6 11:40:10 MET 1995
    
rous: Mon Nov  6 11:44:11 MET 1995
    
rous: Mon Nov  6 11:46:10 MET 1995
    repaired sending mail in integrate command
rous: Mon Nov  6 11:50:09 MET 1995
    repaired sending mail in integrate command
rous: Mon Nov  6 11:53:10 MET 1995
    new rbsedit, bug in dgrab
rous: Mon Nov 27 13:36:11 MET 1995
    removed bug from dbgintegrate
rous: Mon Dec  4 10:44:18 MET 1995
    from now on users only have rx permission for files in the archive
rous: Thu Feb 15 20:31:21 MET 1996
    integration message now only after a successful integration
rous: Thu Apr 10 11:06:34 MET DST 1997
    added $RBS_DIR pathprefix to (dbg)build, bugfix (d)free
