#! /bin/sh -e
#
case $# in
0) echo "Usage: dfree filename"; exit 1;;
1) ;;
*) echo "Usage: dfree filename"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
#
#
#
#
cd doc/source
if ( test -s  $1 )
then if ( test -s $RBS_ARCHIVE$RBS_RELEASE/doc/sccs/s.$1.ascii )
     then sccs -d$RBS_ARCHIVE$RBS_RELEASE/doc -psccs unedit $1.ascii 1> /dev/null 2>&1
        mv $1 /tmp/$1.$$
        chmod 777 /tmp/$1.$$
        rm -f $1.ascii
     else echo "DFREE: File does not exist in the archive!"
          exit
     fi
else echo "DFREE: File not in your source directory!"
     exit 
fi
#
#
#
cd $savedir
trap 0
