#! /bin/sh -e
#
case $# in
0) echo "Usage: fget componentname filename"; exit 1;;
1) echo "Usage: fget componentname filename"; exit 1;;
2) ;;
3) echo "Usage: fget componentname filename"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
#
trap 'echo "FGRAB: Could not grab file $2"; cd $savedir; exit 1' 0
#
fname=`$RBS_DIR/get_fname RBS_logicals $1 $2`
if ( test -z "$fname" )
then
   echo "FGRAB: File does not exists in archive path"
   exit
else 
   echo "FGRAB: grabbing file $fname"
fi
#
create $1 $2
#
grab $1 $2
#
if ( test "$1" = "actions" )
then rm -f $1/$2
     cp $fname $1/$2
else rm -f $1/source/$2
     cp $fname $1/source/$2
fi 
#
trap 0
cd $savedir
