#! /bin/sh -e
#
case $# in
0) echo "Usage: free componentname filename"; exit 1;;
1) echo "Usage: free componentname filename"; exit 1;;
2) ;;
*) echo "Usage: free componentname filename"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
#
#
#
trap '' 1 2 3
#
trap 'echo "FREE: No free allowed during your other frees"; umask 22; cd $savedir; exit 2' 0
umask 222
( echo "  " > $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/free.rbs ) 2> /dev/null
umask 22
#
#
set -e
trap 'echo "FREE: No free allowed during your integrate"; rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/free.rbs ; cd $savedir; exit 2' 0
if ( test -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/integrate.rbs )
then exit 0
fi
#
#
set -e 
trap 'echo "FREE: Error during free" ; rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/free.rbs ; cd $savedir ; exit 2' 0
##
#
#
if ( test "$1" = "actions" )
then cd actions
else cd $1/source
fi
if ( test -r $2 )
then if ( test -s $RBS_ARCHIVE$RBS_RELEASE/$1/sccs/s.$2 )
     then  chmod u+rwx $2
           sccs -d$RBS_ARCHIVE$RBS_RELEASE/$1 -psccs unedit $2 1> /dev/null 2>&1
           mv $2 /tmp/$2.$$
           chmod 777 /tmp/$2.$$
     else echo "FREE: File does not exist in the archive!"
          exit
     fi 
else echo "FREE: File not in your source directory!"
     exit  
fi
#
#
#
rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/free.rbs
cd $savedir
trap 0
