#! /bin/sh -e
case $# in
0) echo "Usage: tmodify componentname filename"; exit 1;;
1) echo "Usage: tmodify componentname filename"; exit 1;;
2) ;;
*) echo "Usage: tmodify componentname filename"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
# 
#
echo " " > $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/modify$$.rbs
set -e
trap 'echo "TMODIFY: No modify allowed during your integrate"; rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/modify$$.rbs; cd $savedir; exit' 0
if ( test -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/integrate.rbs )
then exit 0
fi
#
#
#
#
#
if ( test -s  $1/target/$2 ) || ( test -s actions/$2 )
then 
  if ( test "$1" = "actions" )
  then ( $RBS_EDITOR $1/$2 ; rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/modify$$.rbs
) &
  else ( $RBS_EDITOR $1/target/$2 ; rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/modify$$.rbs ) &
     fi
else 
   echo "TMODIFY: File does not exist in your target directory!"
   rm -f $RBS_USER_ROOT$RBS_USER$RBS_RELEASE/modify$$.rbs
fi
#
cd $savedir
trap 0
