#! /bin/sh -e
#
# lrbs <component> <executable>
#
#
echo "lrbs: $1:$2"
#
trap 'echo "lrbs: Error during linking" ; exit 1' 0
#
$RBS_DIR/mopt $1 $2
rm -f linkfile
echo "#! /bin/sh -e" > linkfile
echo "cc  \\" >> linkfile
#
fname=`get_fname RBS_logicals $1 $2.opt`
if test "$fname"
then cat $fname >> linkfile
else echo "OPT: Could not find file $2.opt"
     exit
fi
#
echo "-o $1/target/$2.exe \\" >> linkfile
#
chmod u+x linkfile
echo "  "  >> warnings
linkfile
#
trap 0
 
