#! /bin/sh
#set -x
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
wrongo=""
directs=`ls -d *`
for i in $directs; do
   if ( test -d $i ) 
   then 
       if ( test "$i" = "doc" )
       then echo "CHECK: skipping component $i"
       elif ( test "$i" = "actions" )
       then echo "CHECK: checking directory $i"
             cd actions
             for j in `ls` ; do
                case $j in
                *sccs) ;;
                *%) ;;
                *~) ;;
                *) k=`basename $j`
                   { test -s $RBS_ARCHIVE$RBS_RELEASE/$i/sccs/s.$k ; } || \
                   { echo "CHECK: ---- Strange source file $k in component $i -- "; wrongo="$k"; }
                   if ( test -s $RBS_ARCHIVE$RBS_RELEASE/$i/sccs/p.$k )
                   then
                      grb=`grep $USER $RBS_ARCHIVE$RBS_RELEASE/$i/sccs/p.$k`
                      if ( test -z "$grb")
                      then echo "CHECK: ---- File $k in component $i not grabbed! -----"
                           wrongo="$k"
                      fi
                   else
                       echo "CHECK: ---- File $k in component $i not grabbed! -----"
                       wrongo="$k"
                   fi ;;
                esac
             done
             cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
        else echo "CHECK: checking directory $i/source"
             cd $i/source
             for j in `ls` ; do
                case $j in
                *sccs) ;;
                *%) ;;
                *~) ;;
                *) k=`basename $j`
                   { test -s $RBS_ARCHIVE$RBS_RELEASE/$i/sccs/s.$k ; } || \
                   { echo "CHECK: ---- Strange source file $k in component $i -- "; wrongo="$k"; }
                   if ( test -s $RBS_ARCHIVE$RBS_RELEASE/$i/sccs/p.$k )
                   then
                      grb=`grep $USER $RBS_ARCHIVE$RBS_RELEASE/$i/sccs/p.$k`
                      if ( test -z "$grb")
                      then echo "CHECK: ---- File $k in component $i not grabbed! -----"
                           wrongo="$k"
                      fi
                   else
                       echo "CHECK: ---- File $k in component $i not grabbed! -----"
                       wrongo="$k"
                   fi ;;
                esac
             done
             cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
         fi
   fi
done
#
cd $savedir
#
if ( test -z "$wrongo" )
then echo "CHECK: Checking finished: source directories OK"
else echo "CHECK: Checking finished: I found at least one illegal file!"
     exit 1
fi
