#! /bin/sh -e
case $# in
0) echo "Usage: dinspect filename"; exit 1;;
1) ;;
*) echo "Usage: dinspect filename"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
# 
#
set -e
trap 'cd $savedir; exit' 0
#
#
#
#
#
if ( test -s $RBS_ARCHIVE$RBS_RELEASE/doc/$1 )
then cp $RBS_ARCHIVE$RBS_RELEASE/doc/$1 /tmp/$$.$1
     chmod 777 /tmp/$$.$1
     $RBS_DEDITOR /tmp/$$.$1
else echo "DINSPECT: File does not exist in archive directory!"
fi
#
cd $savedir
trap 0
