#! /bin/sh -e
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
if ( test -d "doc" )
then echo "Directory <doc> already exists"
else mkdir doc
     cd doc
     mkdir source
     mkdir save
     mkdir target
fi
cd $savedir
exit
