#! /bin/sh -e
#
case $# in
0) echo "Usage: shold componentname filename"; exit 1;;
1) echo "Usage: shold componentname filename"; exit 1;;
2) ;;
*) echo "Usage: shold componentname filename"; exit 1;;
esac
savedir=`pwd`
cd $RBS_USER_ROOT$RBS_USER$RBS_RELEASE
#
#
#
sccs -d$RBS_ARCHIVE$RBS_RELEASE/$1 -psccs prs -e $2
#
#
cd $savedir
trap 0
